Fix babel-runtime error
Trying to import the package failed with the following error:
`Error: Cannot find module 'babel-runtime/helpers/get'`

This commit moves the `babel-runtime` package to dependencies
to fix the error.

Note: reindex-cli and reindex-starter-kit were not affected because
they depend on babel-runtime themselves.